#!/opt/pwn.college/python

import subprocess


print("== INCOMPLETE PLEASE IGNORE ==")

command = "ruff check --select F401 /challenge/simple_siem.py"

try:
    subprocess.run(command, shell=True, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    print("All checks passed!")
    print("You've completed the tutorial! Printing your flag below...\n")
    with open("/flag") as f:
        print(f.read())
except subprocess.CalledProcessError as exc:
    res = exc.output
    print("There are still issues with your code. This is the error from ruff: ")
    print(res)
    print("Try again!")

print("====================================================")