#!/opt/pwn.college/python

import subprocess


print("Welcome to the refactoring module! This challenge will serve as a tutorial to how you will mainly",
    "be completing the challenges in this module.\n")

print("These challenges will ask you to refactor certain aspects of each challenge's provided 'codebase'. In",
    "this scenario, you will be refactoring a simplified version of a security information and event management",
    "(SIEM) solution, or simply a logging solution. Examples of these include Splunk, Datadog, and Wazuh.\n")

print("To assist with these refactoring challenges, we will introduce you to the 'ruff' linter that will",
    "be checking your code to adhere to certain properties. You will be told what needs to be refactored,",
    "as if this is your first week on the job. To learn more about ruff: https://docs.astral.sh/ruff/.\n")

print("This Python executable, 'checker', will be present in every level to give you instructions on what to",
    "do. Be sure to also read the description of the challenge for some more details! Each time you would like",
    "check if you have completed the challenge or get the instructions, run 'checker' again.\n")

print("In this tutorial, all you have to do is remove the unused imports in 'simple_siem.py'.")

print("This challenge will run the following command against 'simple_siem.py': \n")
print("$ ruff check --select F401 /challenge/simple_siem.py\n")

print("Let's break down this command: \n", 
    "\t* 'check' - the basic option telling ruff to lint some code.\n",
    "\t* '--select' - an option to specify ruff to check only certain rules.\n",
    "\t* 'F401' - a lint rule defined by ruff, 'unused-import', which you can read more about here: https://docs.astral.sh/ruff/rules/unused-import/.\n",
    "\t* '/challenge/simple_siem.py' - specify the exact file you want ruff to lint.\n") 
print("We won't always have this in-depth breakdown, so you may have to do your own research in later challenges, which we encourage!\n")

print("====================================================")
print("Now running the above command...\n")

command = "ruff check --select F401 /challenge/simple_siem.py"

try:
    subprocess.run(command, shell=True, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    print("All linter checks passed!")
    print("You've completed the challenge! Printing your flag below...\n")
    with open("/flag") as f:
        print(f.read())
except subprocess.CalledProcessError as exc:
    res = exc.output
    print("There are still issues with your code. This is the error from ruff: ")
    print(res)
    print("Try again!")

print("====================================================")